// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpzwiZbsdxd4C8ouHlh1fzuaTK7F_P_Ew',
    appId: '1:101100602179:web:b37a2d9cebcd51d3dca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    authDomain: 'spot-holder.firebaseapp.com',
    storageBucket: 'spot-holder.appspot.com',
    measurementId: 'G-X6M50H8H71',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE3TYpvaGcsniFZKx7SVgHFyrfMA22G0w',
    appId: '1:101100602179:android:a2060d609866363fdca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    storageBucket: 'spot-holder.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5FgXnmNPOVo69vHPb94r3IMkf-fVI7jo',
    appId: '1:101100602179:ios:ee53ee78717e97ebdca5f6',
    messagingSenderId: '101100602179',
    projectId: 'spot-holder',
    storageBucket: 'spot-holder.appspot.com',
    iosBundleId: 'idanhair.com.app',
  );
}
